### ISSUE TITLE
No support for default struct values

### ISSUE THREAD

**Issue by ebroder** [evanphx/stark#28]
With the thrift gem, creating an instance of a struct without supplying a value for a field which has a default causes the struct to be instantiated with that default:

```
evan@caron:~$ cat test.thrift 
struct Test {
  1: required string a;
  2: optional string b = 'hi';
}
evan@caron:~$ pry
[1] pry(main)> require 'thrift'
=> true
[2] pry(main)> require './test_types'
=> true
[3] pry(main)> t = Test.new
=> <Test a:nil, b:"hi">
[4] pry(main)> t.b
=> "hi"
```

By contrast, stark appears to currently do nothing with default values, causing them to be initialized to nil.

```
evan@caron:~$ pry
[1] pry(main)> require 'stark'
=> true
[2] pry(main)> Stark.materialize('test.thrift')
=> nil
[3] pry(main)> t = Test.new
=> #<Test:0x000000025bffe8>
[4] pry(main)> t.b
=> nil
```

**Comment by evanphx** [comment]
It's been years, and you probably aren't even using this gem anymore, but if you are. Please let me know and I'll see about fixing that.
